"""Rename capsules

Revision ID: bc9bc0d4b969
Revises: cf8e08b474c2
Create Date: 2026-01-03 00:44:28.077281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc9bc0d4b969'
down_revision: Union[str, Sequence[str], None] = 'cf8e08b474c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capsules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('unlock_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notify_email', sa.Boolean(), nullable=True),
    sa.Column('is_email_set', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capsules_id'), 'capsules', ['id'], unique=False)
    op.drop_index(op.f('ix_capsule_id'), table_name='capsule')
    op.drop_table('capsule')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capsule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('unlock_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('notify_email', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_email_set', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('capsule_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('capsule_pkey'))
    )
    op.create_index(op.f('ix_capsule_id'), 'capsule', ['id'], unique=False)
    op.drop_index(op.f('ix_capsules_id'), table_name='capsules')
    op.drop_table('capsules')
    # ### end Alembic commands ###
